/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package ch.admin.bit.jeap.processarchive.test.decree.v1;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

import java.util.Map;
import java.util.Optional;

import static java.util.Map.entry;

@org.apache.avro.specific.AvroGenerated
public class Decree extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -171530637533066220L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Decree\",\"namespace\":\"ch.admin.bit.jeap.processarchive.test.decree.v1\",\"fields\":[{\"name\":\"payload\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static SpecificData MODEL$ = new SpecificData();

    public static final int ARCHIVE_TYPE_VERSION = 1;
    public static final String ARCHIVE_TYPE_NAME = "Decree";
    public static final String SYSTEM_NAME = "JME";
    public static final String REFERENCE_ID_TYPE = "ch.admin.bit.jeap.audit.type.JmeDecreeArtifact";
    public static final int EXPIRATION_DAYS = 30;
    public static final String REGISTRY_URL = "https://bitbucket.bit.admin.ch/scm/bit_jme/jme-archive-type-registry.git";
    public static final String REGISTRY_BRANCH = "feature/JEAP-6074";
    public static final String REGISTRY_COMMIT = "8a20270e772008f8458949cc995cc650d69a98d9";
    public static final String ENCRYPTION_KEY_ID = "jme-process-archive-example-key";

    public static final Map
            <String, Object> ARCHIVE_TYPE_METADATA = Map.ofEntries(
            entry("archiveTypeVersion", ARCHIVE_TYPE_VERSION),
            entry("archiveTypeName", ARCHIVE_TYPE_NAME),
            entry("systemName", SYSTEM_NAME),
            entry("schema", SCHEMA$),
            entry("referenceIdType", REFERENCE_ID_TYPE),
            entry("expirationDays", EXPIRATION_DAYS),
            entry("registryUrl", REGISTRY_URL),
            entry("registryBranch", REGISTRY_BRANCH),
            entry("registryCommit", REGISTRY_COMMIT),
            entry("encryptionKeyId", ENCRYPTION_KEY_ID));

    public Map
            <String, Object> metadata() {
        return ARCHIVE_TYPE_METADATA;
    }

    private static final BinaryMessageEncoder<Decree> ENCODER =
            new BinaryMessageEncoder<Decree>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<Decree> DECODER =
            new BinaryMessageDecoder<Decree>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<Decree> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<Decree> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<Decree> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<Decree>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this Decree to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a Decree from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a Decree instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static Decree fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private String payload;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public Decree() {
    }

    /**
     * All-args constructor.
     *
     * @param payload The new value for payload
     */
    public Decree(String payload) {
        this.payload = payload;
    }

    public SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public Object get(int field$) {
        switch (field$) {
            case 0:
                return payload;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, Object value$) {
        switch (field$) {
            case 0:
                payload = (String) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'payload' field.
     *
     * @return The value of the 'payload' field.
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Gets the value of the 'payload' field as an Optional&lt;java.lang.String&gt;.
     *
     * @return The value wrapped in an Optional&lt;java.lang.String&gt;.
     */
    public Optional<String> getOptionalPayload() {
        return Optional.<String>ofNullable(payload);
    }

    /**
     * Sets the value of the 'payload' field.
     *
     * @param value the value to set.
     */
    public void setPayload(String value) {
        this.payload = value;
    }

    /**
     * Creates a new Decree RecordBuilder.
     *
     * @return A new Decree RecordBuilder
     */
    public static Builder newBuilder() {
        return new Builder();
    }

    /**
     * Creates a new Decree RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new Decree RecordBuilder
     */
    public static Builder newBuilder(Builder other) {
        if (other == null) {
            return new Builder();
        } else {
            return new Builder(other);
        }
    }

    /**
     * Creates a new Decree RecordBuilder by copying an existing Decree instance.
     *
     * @param other The existing instance to copy.
     * @return A new Decree RecordBuilder
     */
    public static Builder newBuilder(Decree other) {
        if (other == null) {
            return new Builder();
        } else {
            return new Builder(other);
        }
    }

    /**
     * RecordBuilder for Decree instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Decree>
            implements org.apache.avro.data.RecordBuilder<Decree> {

        private String payload;

        /**
         * Creates a new Builder
         */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.payload)) {
                this.payload = data().deepCopy(fields()[0].schema(), other.payload);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
        }

        /**
         * Creates a Builder by copying an existing Decree instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(Decree other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.payload)) {
                this.payload = data().deepCopy(fields()[0].schema(), other.payload);
                fieldSetFlags()[0] = true;
            }
        }

        /**
         * Gets the value of the 'payload' field.
         *
         * @return The value.
         */
        public String getPayload() {
            return payload;
        }

        /**
         * Gets the value of the 'payload' field as an Optional&lt;java.lang.String&gt;.
         *
         * @return The Optional&lt;value&gt;.
         */
        public Optional<String> getOptionalPayload() {
            return Optional.<String>ofNullable(payload);
        }

        /**
         * Sets the value of the 'payload' field.
         *
         * @param value The value of 'payload'.
         * @return This builder.
         */
        public Builder setPayload(String value) {
            validate(fields()[0], value);
            this.payload = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'payload' field has been set.
         *
         * @return True if the 'payload' field has been set, false otherwise.
         */
        public boolean hasPayload() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'payload' field.
         *
         * @return This builder.
         */
        public Builder clearPayload() {
            payload = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public Decree build() {
            try {
                Decree record = new Decree();
                record.payload = fieldSetFlags()[0] ? this.payload : (String) defaultValue(fields()[0]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<Decree>
            WRITER$ = (org.apache.avro.io.DatumWriter<Decree>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<Decree>
            READER$ = (org.apache.avro.io.DatumReader<Decree>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeString(this.payload);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.payload = in.readString();

        } else {
            for (int i = 0; i < 1; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.payload = in.readString();
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}










